//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PRODUTO
{
    public int PRO_ID { get; set; }
    public string PRO_NOME { get; set; }
    public Nullable<decimal> PRO_VRVENDA { get; set; }
    public Nullable<decimal> PRO_VRCUSTO { get; set; }
    public int PRO_UNID { get; set; }
}
